from ext.database import base, engine, Session, db
from models import Act, Atv, Nail
import datetime


def dropdb():
    base.metadata.drop_all(engine)

def createdb():
    base.metadata.create_all(engine)

def insertdb():
    with Session() as session:
        #session.add(Act(id=1,dt=datetime.datetime(2023,1,17,18,2,0,0),usr='269592803602989058',ido='',sn='4D4B5047B4964348',ctr='65628',cto='M08'))
        #session.add(Nail(id=5,dt=datetime.datetime(2024,9,14,11,0,0,0),pr=40))
        session.commit()

def deletedb():
    with Session() as session:
        #session.query(Act).filter(Act.id == 100).delete()
        session.commit()

def updatedb():
    with Session() as session:
        #session.query(Act).filter(Act.id == 1).update({'id':1})
        #session.query(Nail).filter(Nail.id == 9).update({'id':10})
        #session.query(Nail).filter(Nail.id == 5).update({'dt':datetime.datetime(2024,9,13,14,0,0,0)})
        session.commit()

{
    "data":[
        {
            "carbohydrates":[
                {
                    "arroz":[
                        {
                            "nm":"bom prato",
                            "kc":0,
                            "pr":[
                                {
                                    "up":26.49,
                                    "dw":23.99
                                }
                            ]
                        },
                        {
                            "nm":"pagliarin",
                            "kc":0,
                            "pr":[
                                {
                                    "up":26.79,
                                    "dw":26.79
                                }
                            ]
                        }
                    ]
                },
                {
                    "feijao":[
                        {
                            "nm":"macio",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "macarrao":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "batata":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "pao":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "psyllium":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "protein":[
                {
                    "carnes":[
                        {
                            "aves":[
                                {
                                    "peito":[
                                        {
                                            "nm":"",
                                            "kc":0,
                                            "pr":[
                                                {
                                                    "up":0,
                                                    "dw":0
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "figado":[
                                        {
                                            "nm":"",
                                            "kc":0,
                                            "pr":[
                                                {
                                                    "up":0,
                                                    "dw":0
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "bovina":[
                                {
                                    "mignon":[
                                        {
                                            "nm":"",
                                            "kc":0,
                                            "pr":[
                                                {
                                                    "up":0,
                                                    "dw":0
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "alcatra":[
                                        {
                                            "nm":"",
                                            "kc":0,
                                            "pr":[
                                                {
                                                    "up":0,
                                                    "dw":0
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "maminha":[
                                        {
                                            "nm":"",
                                            "kc":0,
                                            "pr":[
                                                {
                                                    "up":0,
                                                    "dw":0
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "lagarto":[
                                        {
                                            "nm":"",
                                            "kc":0,
                                            "pr":[
                                                {
                                                    "up":0,
                                                    "dw":0
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "patinho":[
                                        {
                                            "nm":"",
                                            "kc":0,
                                            "pr":[
                                                {
                                                    "up":0,
                                                    "dw":0
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "musculo d":[
                                        {
                                            "nm":"",
                                            "kc":0,
                                            "pr":[
                                                {
                                                    "up":27.90,
                                                    "dw":27.90
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "musculo t":[
                                        {
                                            "nm":"",
                                            "kc":0,
                                            "pr":[
                                                {
                                                    "up":0,
                                                    "dw":0
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "fraldinha":[
                                        {
                                            "nm":"arroba porcionada",
                                            "kc":0,
                                            "pr":[
                                                {
                                                    "up":29.90,
                                                    "dw":0
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "figado":[
                                        {
                                            "nm":"",
                                            "kc":0,
                                            "pr":[
                                                {
                                                    "up":10.49,
                                                    "dw":10.49
                                                }
                                            ]
                                        }
                                    ]
                                },
                            ]
                        },
                        {
                            "suina":[
                                {
                                    "nm":"",
                                    "kc":0,
                                    "pr":[
                                        {
                                            "up":0,
                                            "dw":0
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "peixe":[
                        {
                            "tilapia":[
                                {
                                    "nm":"",
                                    "kc":0,
                                    "pr":[
                                        {
                                            "up":0,
                                            "dw":0
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "ovo":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "vegetables":[
                {
                    "cebola":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "alho":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "cenoura":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "tomate":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "cogumelos":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "alface":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "drinks":[
                {
                    "coca cola":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "cafe":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "fruits":[
                {
                    "maca":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "limao":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "morango":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "dairy":[
                {
                    "leite":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "creme de leite":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "queijo cottage":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "requeijao":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "iogurte natural":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "fats":[
                {
                    "pasta de amendoim":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "azeite":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "spice":[
                {
                    "oregano":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "pimenta":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "hygiene":[
                {
                    "sabonete":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "papel higienico":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "sabao em po":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "detergente":[
                        {
                            "nm":"ype",
                            "kc":0,
                            "pr":[
                                {
                                    "up":2.39,
                                    "dw":2.39
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "pantry":[
                {
                    "chocolate em po":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "mel":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "gelatina":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                },
                {
                    "filtro de cafe":[
                        {
                            "nm":"",
                            "kc":0,
                            "pr":[
                                {
                                    "up":0,
                                    "dw":0
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
